language: node_js
node_js:
  - "node"
  - "10"
  - "12"
  - "14"

dist: xenial
sudo: required

addons:
  sonarqube:
    organization: "bluet-github"
jdk:
  - oraclejdk8
script:
  - npm test
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
    - 'coverage/'
